window.languages = {
    en: {
        fact_happy_clients: "Happy Clients",
        fact_projects_done: "Projects Done",
        fact_win_awards: "Win Awards",
        about_title_small: "About Us",
        about_title_main: "Reliable Moving Services With Years of Experience",
        about_description: "Moving to a new home or office can be stressful — and that’s exactly where we come in. We provide fast, safe, and professional moving services across the city. From packing and loading to transportation and unloading, our team handles every step with care. Our goal is to make your moving day smooth, easy, and completely stress-free.",
        about_feature_1: "Fully Insured & Trusted Service",
        about_feature_2: "Experienced & Friendly Movers",
        about_feature_3: "Available 7 Days a Week",
        about_feature_4: "Upfront & Affordable Pricing",
        about_call_us: "Call to ask any question",
        about_request_quote: "Request A Free Quote",
        why_choose_us_title_small: "Why Choose Us",
        why_choose_us_title_main: "Reliable & Professional Moving Services",
        feature_safe_secure_title: "Safe & Secure Moving",
        feature_safe_secure_desc: "Your furniture and belongings are handled with full protection, padding, blankets, and care.",
        feature_affordable_title: "Affordable Pricing",
        feature_affordable_desc: "Transparent and competitive rates — no hidden fees, no surprises.",
        feature_experienced_title: "Experienced Movers",
        feature_experienced_desc: "Our trained and friendly moving crew ensures a smooth and stress-free move.",
        feature_support_title: "24/7 Customer Support",
        feature_support_desc: "Anytime you need us — we’re one call away to assist with your moving needs.",
        services_title_small: "Our Services",
        services_title_main: "Professional Moving Services in Quebec&Toronto",
        service_residential_title: "Residential Moving",
        service_residential_desc: "Safe, fast, and professional home moving services across Quebec&Toronto. Stress-free and reliable relocation.",
        service_office_title: "Office Moving",
        service_office_desc: "Professional relocation for offices and workplaces with minimal downtime and maximum efficiency.",
        service_long_distance_title: "Long-Distance Moving",
        service_long_distance_desc: "Reliable long-distance moving from Quebec&Toronto to any city across Canada. Safe and timely delivery guaranteed.",
        service_furniture_title: "Furniture & Appliance Moving",
        service_furniture_desc: "Professional dismantling, wrapping, and moving of furniture, appliances, and heavy household items.",
        service_packing_title: "Packing Services",
        service_packing_desc: "High-quality packing and protective materials to ensure your belongings stay safe during the move.",
        service_call_title: "Call Us For a Free Quote",
        service_call_desc: "Affordable, efficient, and professional moving services for homes and businesses across Quebec&Toronto.",
        service_call_phone: "+1 (437) 436-1414",
        pricing_title_small: "Pricing Plans",
        pricing_title_main: "Affordable & Transparent Moving Prices",
        plan_basic_title: "Basic Move",
        plan_basic_subtitle: "For Small Apartments & Rooms",
        plan_basic_rate: "/ Flat Rate",
        plan_basic_item_1: "2 Movers + Truck",
        plan_basic_item_2: "Local Quebec&Toronto Moving",
        plan_basic_item_3: "Packing Assistance",
        plan_basic_item_4: "Furniture Assembly",
        plan_basic_btn: "Book Now",
        plan_standard_title: "Standard Move",
        plan_standard_subtitle: "For 1–2 Bedroom Homes",
        plan_standard_rate: "/ Flat Rate",
        plan_standard_item_1: "2 Movers + Large Truck",
        plan_standard_item_2: "Full Home Moving",
        plan_standard_item_3: "Packing & Wrapping",
        plan_standard_item_4: "Furniture Assembly",
        plan_standard_btn: "Book Now",
        plan_premium_title: "Premium Move",
        plan_premium_subtitle: "For Large Homes & Offices",
        plan_premium_rate: "/ Flat Rate",
        plan_premium_item_1: "3 Movers + XL Truck",
        plan_premium_item_2: "Full Home & Office Moving",
        plan_premium_item_3: "Packing & Unpacking",
        plan_premium_item_4: "Furniture Assembly Included",
        plan_premium_btn: "Book Now",
        quote_title_small: "Request A Quote",
        quote_title_main: "Get Your Free Moving Quote Today",
        quote_description: "Send us your moving details directly to WhatsApp. Fast response guaranteed!",
        quote_call_us: "Call or WhatsApp Anytime",
        quote_phone: "+1 (437) 436-1414",
        quote_input_name: "Your Full Name",
        quote_input_phone: "Phone Number",
        quote_input_email: "Email (Optional)",
        quote_select_move: "Select Move Type",
        move_1b: "1 Bedroom Apartment",
        move_2b: "2 Bedroom Apartment",
        move_3b: "3 Bedroom Apartment",
        move_house: "House Move",
        move_office: "Office Move",
        quote_input_pickup: "Pickup Address",
        quote_input_dropoff: "Drop-off Address",
        quote_input_message: "Additional Details (Optional)",
        quote_btn_whatsapp: "Send via WhatsApp",
        quote_btn_send: "Send Message",
        testimonial_title_small: "Testimonial",
        testimonial_title_main: "What Our Clients Say About Our Moving Services",
        testimonial_1_name: "Emily R.",
        testimonial_1_role: "Home Owner",
        testimonial_1_text: "Very professional and fast service! They packed everything carefully and moved my furniture without a single scratch. Highly recommended!",
        testimonial_2_name: "David M.",
        testimonial_2_role: "Apartment Move",
        testimonial_2_text: "Excellent moving service! The team arrived on time and worked very efficiently. Prices are fair and the quality is top-notch.",
        testimonial_3_name: "Sarah L.",
        testimonial_3_role: "Office Move",
        testimonial_3_text: "They helped us relocate our office smoothly. All equipment was handled safely and assembled in the new location. Great experience!",
        testimonial_4_name: "Michael K.",
        testimonial_4_role: "Local Move",
        testimonial_4_text: "Amazing team! Very respectful and careful with all belongings. The whole move was stress-free thanks to them.",
        team_title_small: "Team Members",
        team_title_main: "Professional Movers Ready to Help You Anytime",
        team_member_1_name: "Joel",
        team_member_1_role: "Driver & Mover",
        team_member_2_name: "Ibo",
        team_member_2_role: "Director & Mover",
        team_member_3_name: "Gasim",
        team_member_3_role: "Mover",
        category_home_moving: "Home Moving",
        category_office_moving: "Office Moving",
        category_packing_tips: "Packing Tips",
        category_moving_trucks: "Moving Trucks",
        category_storage_solutions: "Storage Solutions",
        blog1_title: "Tips for Packing Efficiently",
        blog1_desc: "Learn how to pack your items safely and efficiently to make your move smooth and stress-free.",
        blog2_title: "Planning an Office Move",
        blog2_desc: "Key strategies to plan your office relocation with minimal downtime and maximum efficiency.",
        blog3_title: "How to Protect Fragile Items",
        blog3_desc: "Learn techniques for safely packing and transporting fragile household items.",
        blog4_title: "Choosing the Right Moving Truck",
        blog4_desc: "Tips on selecting the proper truck size for your move to save time and effort.",
        read_more: "Read More",
        search_placeholder: "Search Moving Tips",
        sidebar_categories: "Categories",
        sidebar_recent_posts: "Recent Posts",
        pagination_prev: "Previous",
        pagination_next: "Next",
        navbar: {
            home: "Home",
            about: "About",
            services: "Services",
            blog: "Blog",
            blog_grid: "Blog Grid",
            blog_detail: "Blog Detail",
            pages: "Pages",
            pricing_plan: "Pricing Plan",
            features: "Our features",
            team: "Team Members",
            testimonial: "Testimonial",
            quote: "Free Quote",
            contact: "Contact",
            get_free_quote: "Get Free Quote",
            search: "Search"
        },
        carousel: {
            slide1: {
                subtitle: "Reliable & Efficient",
                title: "Safe & Fast Home Moving Services",
                btn_quote: "Get Free Quote",
                btn_contact: "Contact Us"
            },
            slide2: {
                subtitle: "Professional Movers",
                title: "Efficient Office Relocation Solutions",
                btn_quote: "Get Free Quote",
                btn_contact: "Contact Us"
            },
            prev: "Previous",
            next: "Next"
        }
    },

    fr: {
        fact_happy_clients: "Clients Satisfaits",
        fact_projects_done: "Projets Réalisés",
        fact_win_awards: "Récompenses Gagnées",
        about_title_small: "À propos de nous",
        about_title_main: "Services de déménagement fiables avec des années d'expérience",
        about_description: "Déménager dans une nouvelle maison ou un nouveau bureau peut être stressant — et c’est exactement là que nous intervenons. Nous offrons des services de déménagement rapides, sûrs et professionnels dans toute la ville. De l'emballage et du chargement au transport et au déchargement, notre équipe gère chaque étape avec soin. Notre objectif est de rendre votre journée de déménagement fluide, facile et totalement sans stress.",
        about_feature_1: "Service entièrement assuré et fiable",
        about_feature_2: "Déménageurs expérimentés et amicaux",
        about_feature_3: "Disponible 7 jours sur 7",
        about_feature_4: "Tarification transparente et abordable",
        about_call_us: "Appelez pour toute question",
        about_request_quote: "Demander un devis gratuit",
        why_choose_us_title_small: "Pourquoi nous choisir",
        why_choose_us_title_main: "Services de déménagement fiables et professionnels",
        feature_safe_secure_title: "Déménagement sûr et sécurisé",
        feature_safe_secure_desc: "Vos meubles et effets personnels sont manipulés avec une protection complète, des protections, des couvertures et des soins.",
        feature_affordable_title: "Tarification abordable",
        feature_affordable_desc: "Tarifs transparents et compétitifs — pas de frais cachés, pas de surprises.",
        feature_experienced_title: "Déménageurs expérimentés",
        feature_experienced_desc: "Notre équipe de déménagement formée et sympathique assure un déménagement fluide et sans stress.",
        feature_support_title: "Support client 24/7",
        feature_support_desc: "Chaque fois que vous avez besoin de nous — nous sommes à un appel pour vous aider avec vos besoins de déménagement.",
        services_title_small: "Nos Services",
        services_title_main: "Services de déménagement professionnels à Québec et Toronto",
        service_residential_title: "Déménagement résidentiel",
        service_residential_desc: "Services de déménagement à domicile sûrs, rapides et professionnels à Québec et Toronto. Relocalisation sans stress et fiable.",
        service_office_title: "Déménagement de bureaux",
        service_office_desc: "Relocalisation professionnelle pour les bureaux et lieux de travail avec un minimum d'interruptions et une efficacité maximale.",
        service_long_distance_title: "Déménagement longue distance",
        service_long_distance_desc: "Déménagement longue distance fiable de Québec et Toronto vers n'importe quelle ville du Canada. Livraison sûre et ponctuelle garantie.",
        service_furniture_title: "Déménagement de meubles et appareils",
        service_furniture_desc: "Démontage, emballage et déménagement professionnels des meubles, appareils et objets ménagers lourds.",
        service_packing_title: "Services d'emballage",
        service_packing_desc: "Matériaux d'emballage et de protection de haute qualité pour garantir la sécurité de vos biens pendant le déménagement.",
        service_call_title: "Appelez-nous pour un devis gratuit",
        service_call_desc: "Services de déménagement abordables, efficaces et professionnels pour les maisons et les entreprises à Québec et Toronto.",
        service_call_phone: "+1 (437) 436-1414",
        pricing_title_small: "Plans tarifaires",
        pricing_title_main: "Prix de déménagement abordables et transparents",
        plan_basic_title: "Déménagement Basique",
        plan_basic_subtitle: "Pour petits appartements & chambres",
        plan_basic_rate: "/ Tarif forfaitaire",
        plan_basic_item_1: "2 déménageurs + camion",
        plan_basic_item_2: "Déménagement local Québec & Toronto",
        plan_basic_item_3: "Assistance à l'emballage",
        plan_basic_item_4: "Assemblage de meubles",
        plan_basic_btn: "Réserver",
        plan_standard_title: "Déménagement Standard",
        plan_standard_subtitle: "Pour maisons 1–2 chambres",
        plan_standard_rate: "/ Tarif forfaitaire",
        plan_standard_item_1: "2 déménageurs + grand camion",
        plan_standard_item_2: "Déménagement complet de la maison",
        plan_standard_item_3: "Emballage & Protection",
        plan_standard_item_4: "Assemblage de meubles",
        plan_standard_btn: "Réserver",
        plan_premium_title: "Déménagement Premium",
        plan_premium_subtitle: "Pour grandes maisons & bureaux",
        plan_premium_rate: "/ Tarif forfaitaire",
        plan_premium_item_1: "3 déménageurs + camion XL",
        plan_premium_item_2: "Déménagement complet maison & bureau",
        plan_premium_item_3: "Emballage & Déballage",
        plan_premium_item_4: "Assemblage de meubles inclus",
        plan_premium_btn: "Réserver",
        quote_title_small: "Demander un devis",
        quote_title_main: "Obtenez votre devis de déménagement gratuit aujourd'hui",
        quote_description: "Envoyez-nous les détails de votre déménagement directement sur WhatsApp. Réponse rapide garantie !",
        quote_call_us: "Appelez ou WhatsApp à tout moment",
        quote_phone: "+1 (437) 436-1414",
        quote_input_name: "Nom complet",
        quote_input_phone: "Numéro de téléphone",
        quote_input_email: "Email (facultatif)",
        quote_select_move: "Sélectionner le type de déménagement",
        move_1b: "Appartement 1 chambre",
        move_2b: "Appartement 2 chambres",
        move_3b: "Appartement 3 chambres",
        move_house: "Déménagement de maison",
        move_office: "Déménagement de bureau",
        quote_input_pickup: "Adresse de départ",
        quote_input_dropoff: "Adresse de livraison",
        quote_input_message: "Détails supplémentaires (facultatif)",
        quote_btn_whatsapp: "Envoyer via WhatsApp",
        quote_btn_send: "Envoyer le message",
        testimonial_title_small: "Témoignage",
        testimonial_title_main: "Ce que nos clients disent de nos services de déménagement",
        testimonial_1_name: "Emily R.",
        testimonial_1_role: "Propriétaire",
        testimonial_1_text: "Service très professionnel et rapide ! Ils ont emballé tous mes meubles avec soin et les ont déplacés sans une seule rayure. Fortement recommandé !",
        testimonial_2_name: "David M.",
        testimonial_2_role: "Déménagement d'appartement",
        testimonial_2_text: "Excellent service de déménagement ! L'équipe est arrivée à l'heure et a travaillé très efficacement. Les prix sont justes et la qualité est exceptionnelle.",
        testimonial_3_name: "Sarah L.",
        testimonial_3_role: "Déménagement de bureau",
        testimonial_3_text: "Ils nous ont aidés à déménager notre bureau en toute sérénité. Tout l'équipement a été manipulé en toute sécurité et assemblé dans le nouveau lieu. Excellente expérience !",
        testimonial_4_name: "Michael K.",
        testimonial_4_role: "Déménagement local",
        testimonial_4_text: "Équipe incroyable ! Très respectueuse et attentive avec tous les biens. Tout le déménagement s'est déroulé sans stress grâce à eux.",
        team_title_small: "Membres de l'équipe",
        team_title_main: "Déménageurs professionnels prêts à vous aider à tout moment",
        team_member_1_name: "Joel",
        team_member_1_role: "Chauffeur & Déménageur",
        team_member_2_name: "Ibo",
        team_member_2_role: "Directeur & Déménageur",
        team_member_3_name: "Gasim",
        team_member_3_role: "Déménageur",
        category_home_moving: "Déménagement à domicile",
        category_office_moving: "Déménagement de bureau",
        category_packing_tips: "Conseils d'emballage",
        category_moving_trucks: "Camions de déménagement",
        category_storage_solutions: "Solutions de stockage",
        blog1_title: "Conseils pour un emballage efficace",
        blog1_desc: "Apprenez à emballer vos affaires en toute sécurité et efficacement pour que votre déménagement se déroule sans stress.",
        blog2_title: "Planification d'un déménagement de bureau",
        blog2_desc: "Stratégies clés pour planifier le déménagement de votre bureau avec un minimum d'interruption et une efficacité maximale.",
        blog3_title: "Comment protéger les objets fragiles",
        blog3_desc: "Apprenez des techniques pour emballer et transporter en toute sécurité les objets fragiles de votre maison.",
        blog4_title: "Choisir le bon camion de déménagement",
        blog4_desc: "Conseils pour sélectionner la taille appropriée du camion pour votre déménagement afin de gagner du temps et des efforts.",
        read_more: "Lire la suite",
        search_placeholder: "Rechercher des conseils de déménagement",
        sidebar_categories: "Catégories",
        sidebar_recent_posts: "Articles récents",
        pagination_prev: "Précédent",
        pagination_next: "Suivant",
        navbar: {
            home: "Accueil",
            about: "À propos",
            services: "Services",
            blog: "Blog",
            blog_grid: "Grille du blog",
            blog_detail: "Détail du blog",
            pages: "Pages",
            pricing_plan: "Plan tarifaire",
            features: "Nos fonctionnalités",
            team: "Membres de l'équipe",
            testimonial: "Témoignages",
            quote: "Devis gratuit",
            contact: "Contact",
            get_free_quote: "Obtenez un devis gratuit",
            search: "Rechercher"
        },
        carousel: {
            slide1: {
                subtitle: "Fiable et efficace",
                title: "Services de déménagement rapides et sécurisés",
                btn_quote: "Obtenez un devis gratuit",
                btn_contact: "Contactez-nous"
            },
            slide2: {
                subtitle: "Déménageurs professionnels",
                title: "Solutions efficaces pour le déménagement de bureau",
                btn_quote: "Obtenez un devis gratuit",
                btn_contact: "Contactez-nous"
            },
            prev: "Précédent",
            next: "Suivant"
        }
    }
};
